### PR TITLE
Add the FrameTime callback

### PR DESCRIPTION
**Pull request by RobLoach**
Attempt to add the frame_time callback, to let cores know how much time has passed between frames. This has not been tested yet, as I haven't gotten it to compile yet. Would love your help on getting it to work.

It should use Kodi's frame time delta rather than ctime. Also, is RunFrame the right place to call this?

There's an example of its use over at [sdlarch.c](https://github.com/heuripedes/sdlarch/blob/master/sdlarch.c#L774-L783).

### CODE REVIEW

**Comment by garbear** [comment]
> It should use Kodi's frame time delta rather than ctime.

Can you explain why?

> Also, is RunFrame the right place to call this?

The documentation says:

https://github.com/kodi-game/game.libretro/blob/master/src/libretro/libretro.h#L1783

```
It will be called right before retro_run() every frame.
```

**Comment by RobLoach** [comment]
Kodi may have a better API to get accurate tick count? Unsure if clock is the right thing to use here.

**Comment by garbear** [comment]
I don't understand. Isn't FF/RW controlled by Kodi? How does exposing the frame time give cores control over this?

**Comment by RobLoach** [comment]
Not sure, to be honest! Maybe `clock()` is the way to go.

**Comment by garbear** [comment]
What cores use this feature?

**Comment by RobLoach** [comment]
ChaiLove does, to calculate the step time:
https://github.com/libretro/libretro-chailove/blob/master/src/libretro.cpp#L286-L290

**Comment by RobLoach** [comment]
Closing this one for now. Feel free to re-open if it tickles your fancy.

**Pull request closed without merging**
