### PR TITLE
[ci] use osx xcode 9 & 9.3 images

### PR DESCRIPTION
**Pull request by Rechi**
Jenkins uses xcode 9 already for 3 months

### CODE REVIEW

**Comment by Rechi** [comment]
@garbear ping

**Comment by garbear** [comment]
Can you also update the template at https://github.com/fetzerch/kodi-game-scripting/blob/master/templates/addon/.travis.yml.j2?

**Comment by Rechi** [comment]
@fetzerch can you do the update for all addons?

**Comment by fetzerch** [comment]
Sure: https://github.com/fetzerch/kodi-game-scripting/commit/41703e2f44941b6ebb5bd7e265641c76eed70d16

Changes are pushed at this moment.

**Comment by garbear** [comment]
thanks!

**Pull request merged**
