### PR TITLE
Move buttonmap.xml location to resources/ subdirectory

### PR DESCRIPTION
**Pull request by garbear**
Ref: https://trello.com/c/b8wQGi46/28-move-buttonmap-xml-for-emulator-addons-into-resource-directory

Requires corresponding adjustment to existing libretro add-ons.

### CODE REVIEW

**Comment by garbear** [comment]
@a1rwulf or @montellese, does one of you wanna help out with this over the weekend? we could divide and conquer

**Comment by a1rwulf** [comment]
@garbear I'm not sure if I can make it this WE. But I'll let you know later
today.

**Comment by Montellese** [comment]
Unfortunately my whole weekend is full, sorry.

**Comment by a1rwulf** [comment]
I think I may have some time in a few hours.
I could also care about it entirely and PR all changes so we just have to
push the merge button for all the repos.

**Comment by garbear** [comment]
```bash
#!/bin/bash

for ADDON_ID in game.libretro.2048 \
                game.libretro.mupen64plus \
                game.libretro.bsnes-mercury \
                game.libretro.quicknes \
                game.libretro.yabause \
                game.libretro.vba-next \
                game.libretro.vbam \
                game.libretro.nestopia \
                game.libretro.mgba \
                game.libretro.meteor \
                game.libretro.genplus \
                game.libretro.gambatte \
                game.libretro.fceumm \
                game.libretro.dosbox \
                game.libretro.bnes \
                game.libretro.beetle-pce-fast \
                game.libretro.stella \
                game.libretro.beetle-gba \
                game.libretro.beetle-bsnes;
do
    git clone git@github.com:kodi-game/$ADDON_ID.git
    cd $ADDON_ID/$ADDON_ID
    if [ -f buttonmap.xml ]; then
        mkdir -p resources
        git mv buttonmap.xml resources/ && \
        git commit -m "[buttonmap.xml] Move to resources/" && \
        git push
    fi
    cd ../..
done
```

**Pull request merged**
