### PR TITLE
Implementing support for Achievements in RetroPlayer

### PR DESCRIPTION
**Pull request by Shardul555**
This PR implement support for Achievements in ReteroPlayer. This PR is based on #67 , for adding support of RCheevos.
This PR is used by [garbear-xbmc #126](https://github.com/garbear/xbmc/pull/126) for implementing Achievements.

### CODE REVIEW

**Comment by Hedda** [comment]
Any updates/news on https://github.com/kodi-game/game.libretro/pull/73 and https://github.com/garbear/xbmc/pull/126 or https://github.com/garbear/xbmc/pull/127 now that https://github.com/kodi-game/game.libretro/pull/67 has been merged?

**Comment by garbear** [comment]
@NikosSiak is upstreaming his GSoC 2020 work. We'll return to GSoC 2021 after.

**Comment by garbear** [comment]
@Shardul555 It's time! Can you cherry-pick 1ed068e689abd30d0d9eb8be5bc379e9609660f7 and open a new PR against the `Omega` branch?

**Comment by Shardul555** [comment]
Hi Garbear,

I have opened a PR: https://github.com/kodi-game/game.libretro/pull/104
Please review it whenever possible.

Thanks and Regards,
Shardul Semwal

**Comment by garbear** [comment]
Superseded by https://github.com/kodi-game/game.libretro/pull/104

**Pull request closed without merging**
