### PR TITLE
Internal depends

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR is a continuation of https://github.com/kodi-game/game.libretro/pull/93. I cherry-picked all the work and rebased on the Nexus branch.

## How has this been tested?

Starting to test now.

Jenkins looks good: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro/detail/PR-101/1/pipeline

### CODE REVIEW

**Comment by garbear** [comment]
Rebased on https://github.com/kodi-game/game.libretro/pull/102, CI is looking good again

**Comment by garbear** [comment]
Also ping @wsnipex for review, this starts our journey of fixing all the missing dependency issues in our ppa

**Review by wsnipex — APPROVED** [review]
looks good, builds: https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+packages?field.name_filter=kodi-game-libretro&field.status_filter=published&field.series_filter=

**Comment by garbear** [comment]
Cool, looks like v19 is still broken, I'll see if I can backport

**Comment by wsnipex** [comment]
no use for the PPA, older versions won't get built or published anymore

**Comment by garbear** [comment]
Then touch it I don't.

**Pull request merged**
