### PR TITLE
fix thread includes

### PR DESCRIPTION
**Pull request by a1rwulf**
Don't know if this is right.
But until now I struggled trying to get stand-alone builds of the binary addons, this helps for me, though - maybe you can give me some feedback on that.
Actually this could brake in-tree builds when giving a second thought...

### CODE REVIEW

**Comment by akva2** [comment]
this is correct. it is needed after the split of kodi-platform.

can you please add find_package(platform) with friends to cmakelists.txt ?

**Comment by notspiff** [comment]
argh.  notspiff with wrong login ^

**Comment by a1rwulf** [comment]
Sure, I can when I'm at home.
However I'm not sure what you mean by "with friends", is there more needed then the find_package for platform?
Maybe you can be a little more detailed for me here (not that familiar with the system yet)?
Thanks.

**Comment by akva2** [comment]
you need to add the include paths and the link as well.

**Comment by a1rwulf** [comment]
aye - thanks.

**Comment by a1rwulf** [comment]
I've changed now - please have a look again, I'm still quite unsure if I do things right here.

**Comment by garbear** [comment]
I rebased RetroPlayer on beta2. with this change, game.libretro compiles successfully. I'll update peripheral.joystick likewise

**Comment by garbear** [comment]
@notspiff I tried applying the cmake fix to peripheral.joystick: https://github.com/kodi-game/peripheral.joystick/commit/3aa2f3d but I get the following error

```
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "Findplatform.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "platform",
  but CMake did not find one.

  Could not find a package configuration file provided by "platform" with any
  of the following names:

    platformConfig.cmake
    platform-config.cmake
```

**Comment by akva2** [comment]
@garbear kodiplatform was split in two, you also need https://github.com/Pulse-Eight/platform now (a dependency of kodi-platform).

**Comment by garbear** [comment]
awesome thanks, i didn't see any new libs at github.com/xbmc, i'll grab the lib from pulse eight's github

**Pull request merged**
