### PR TITLE
[PPA] Allow internal libretro-common and rcheevos build

### PR DESCRIPTION
**Pull request by fuzzard**

### CODE REVIEW

**Comment by garbear** [comment]
@fuzzard I needed the top three commits from this branch: https://github.com/kodi-game/game.libretro/commits/a1d06cbdbf919be94ee2e25ce32d17fdcb8c1494.

I included the errors that each commit fixes in the description for your quick reference.

**Comment by garbear** [comment]
@fuzzard Got time to cherry-pick and merge?

**Comment by fuzzard** [comment]
Feel free to close and open another one, or see if you can push to my branch.

I'll try have a look tonight or more likely over the weekend otherwise

**Comment by garbear** [comment]
I have no motivation to take this on. In 24hr Hacktoberfest starts and I feel 100% different 😉

**Comment by garbear** [comment]
TADA! now I have motivation. I'm carrying the mantle over at https://github.com/kodi-game/game.libretro/pull/101

**Pull request closed without merging**
