### PR TITLE
[Matrix] metadata sync action

### PR DESCRIPTION
**Pull request by gade01**
This action will automatically sync:
- Summary
- Description
- Disclaimer  

between addon.xml and language files.

When changes are done in either addon.xml or in the language files, the action will open a pull request with the synced changes.

Please merge any open Weblate pull request first.

### CODE REVIEW

**Comment by garbear** [comment]
@gade01 Is this ready? Looks like the workflow yml needs to be updated

**Comment by gade01** [comment]
@garbear Yeah, I'll update the workflow.

**Comment by gade01** [comment]
Created a new one: https://github.com/kodi-game/game.libretro/pull/74

**Comment by garbear** [comment]
FYI you can force-push via git, and the PR will reflect the new state

**Comment by gade01** [comment]
Thanks. Yeah, I know.
I had deleted the fork and everything, which lead me to start all over.

**Pull request closed without merging**
